---
title: Home - State Machine
---
stateDiagram-v2
  state "
    **ENTRY** - *When the user arrives to the home page*
    <h5>
      lockScroll()
      A_T_1()
    </h5>
  " as ENTRY

  state "
    **INTRO** - *When the first animation is done and won't be coming back until refresh*
    <h5>
      lockScroll()
      A_T_2(wheel)
    </h5>
  " as INTRO

  state "
    **CONTENT_APPEAREANCE1** - *When the user can first scroll to the first content*
    <h5>
      unlockScroll()
    </h5>
  " as CONTENT_APPEAREANCE1

  state "
    **Content1** - *When arrives at the end of the first content*
    <h5>
      lockScroll()
      A_C1_1(wheel)
    </h5>
  " as CONTENT1

  [*] --> ENTRY: entry (home page event)

  ENTRY --> INTRO: If A_T_LT is done

  INTRO --> CONTENT_APPEAREANCE1: If A_T_LG is done (meaning wheel at a certain value not yet determined)

  CONTENT_APPEAREANCE1 --> CONTENT1


