---
config:
  layout: elk
---
flowchart LR
  HomePage --> Init
  HomePage --> DOM
  DOM --> User
  User ==>|Events| IB

  subgraph States
    direction TB
    Entry
    Intro
    ContentAppearance1
    Content1
  end

  subgraph SH[StateHandlers]
    direction TB
    EntryHandler
    IntroHandler
    ContentAppearance1Handler
    Content1Handler
  end

  subgraph StateMachine[**StateMachine**]
    States <==> SH
    Effects
    Init
  end

  Effects -.-|=| SH

  subgraph Animations
    A_T_1[
      TitleEntryLinesTranslating :
      on => entry
      with => fade, translation, keyFrame
    ]
    A_T_2[
      TitleLinesGrowthLineGradient :
      on => scroll/wheel
      with => width, height, background, keyFrame
    ]
    A_C1_1[
      Content1LineGrowthLineGradient :
      on => scroll/wheel
      with => width, height, background, keyFrame, @if, fade
    ]
  end

  EntryHandler ==> A_T_1
  IntroHandler ==> A_T_2
  Content1Handler ==> A_C1_1

  Animations ==> DOM

  HomePage --> Bindings
  Bindings --> IB

  subgraph IB[**Input bindings**]
    Wheel --> WheelValue
    WheelValue --> SH

    Scroll --> ScrollValue
    ScrollValue --> SH

    subgraph combinedLatest
      subgraph throttleTime
        Wheel
        Scroll
      end
    end
  end

  HomePage[<h2>HomePage</h2>]
  User[<h2>User</h2>]
  WheelValue[WheelValue: signal]
  ScrollValue[ScrollValue: signal]
